name = "Startbootstrap Clean Blog"
license = "MIT"
#licenselink = "https://github.com/humboldtux/startbootstrap-clean-blog/blob/master/LICENSE.md"
description = "Startbootstrap Clean Theme"
homepage = "https://github.com/yambay/hugo-bootstrap-clean-theme"
tags = ["blog", "bootstrap", "clean"]
features = ["blog", "bootstrap", "clean"]
min_version = 0.18

[author]
  name = "Ilyas Yambay"
  homepage = "http://www.y2a.me"

# original theme
[original]
  name = "Startbootstrap Clean Blog"
  homepage = "http://startbootstrap.com/template-overviews/clean-blog/"
  repo = "https://github.com/IronSummitMedia/startbootstrap-clean-blog"